import type { Equipment } from "@/lib/types";

const equipmentDefaults: Pick<
  Equipment,
  | "brand"
  | "model"
  | "secondary_muscles"
  | "angle"
  | "is_unilateral"
  | "is_plate_loaded"
  | "is_selectorized"
  | "is_cable"
  | "stability_level"
  | "fatigue_score"
  | "setup_difficulty"
  | "handles_grips"
  | "notes"
  | "user_preference"
  | "is_available"
> = {
  brand: "",
  model: "",
  secondary_muscles: [],
  angle: "neutral",
  is_unilateral: false,
  is_plate_loaded: false,
  is_selectorized: false,
  is_cable: false,
  stability_level: "high",
  fatigue_score: "medium",
  setup_difficulty: "low",
  handles_grips: [],
  notes: "",
  user_preference: "neutral",
  is_available: true
};

type EquipmentSeed = Omit<Equipment, keyof typeof equipmentDefaults> &
  Partial<typeof equipmentDefaults>;

function eq(input: EquipmentSeed): Equipment {
  return { ...equipmentDefaults, ...input };
}

export const equipmentCatalog: Equipment[] = [
  eq({
    id: "eq-hs-decline-press",
    name: "Hammer Strength Iso-Lateral Decline Press",
    brand: "Hammer Strength",
    model: "Iso-Lateral Decline Press",
    category: "Chest Press",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["chest"],
    secondary_muscles: ["triceps", "front_delt"],
    target_regions: ["lower_chest", "triceps", "front_delt"],
    movement_patterns: ["decline_press", "iso_lateral_press"],
    movement_family: ["horizontal_push"],
    angle: "decline",
    is_unilateral: true,
    is_plate_loaded: true,
    fatigue_score: "medium_high",
    handles_grips: ["neutral handles"],
    user_preference: "preferred",
    notes: "High-stability lower chest press with independent arms."
  }),
  eq({
    id: "eq-incline-chest-press",
    name: "Incline Chest Press Machine",
    category: "Chest Press",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["chest"],
    secondary_muscles: ["front_delt", "triceps"],
    target_regions: ["upper_chest", "front_delt", "triceps"],
    movement_patterns: ["incline_press"],
    movement_family: ["horizontal_push"],
    angle: "incline",
    is_selectorized: true,
    handles_grips: ["neutral handles", "pronated handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-plate-loaded-chest-press",
    name: "Plate Loaded Chest Press",
    category: "Chest Press",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["chest"],
    secondary_muscles: ["triceps", "front_delt"],
    target_regions: ["mid_chest", "triceps"],
    movement_patterns: ["flat_press", "machine_press"],
    movement_family: ["horizontal_push"],
    angle: "flat",
    is_plate_loaded: true,
    fatigue_score: "medium_high",
    handles_grips: ["neutral handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-selectorized-chest-press",
    name: "Selectorized Chest Press",
    category: "Chest Press",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["chest"],
    secondary_muscles: ["triceps", "front_delt"],
    target_regions: ["mid_chest", "triceps"],
    movement_patterns: ["flat_press", "close_grip_press"],
    movement_family: ["horizontal_push"],
    angle: "flat",
    is_selectorized: true,
    handles_grips: ["neutral handles", "wide handles"]
  }),
  eq({
    id: "eq-pec-deck",
    name: "Pec Deck",
    category: "Chest Fly",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["chest"],
    secondary_muscles: ["front_delt"],
    target_regions: ["mid_chest"],
    movement_patterns: ["pec_deck_fly", "machine_fly"],
    movement_family: ["fly"],
    is_selectorized: true,
    handles_grips: ["forearm pads", "vertical handles"],
    fatigue_score: "medium"
  }),
  eq({
    id: "eq-dual-cable-station",
    name: "Dual Adjustable Cable Station",
    category: "Cable Station",
    equipment_type: "cable",
    load_type: "cable_stack",
    primary_muscles: ["chest", "lats", "side_delt", "triceps", "biceps"],
    secondary_muscles: ["rear_delt", "abs", "glutes"],
    target_regions: [
      "upper_chest",
      "mid_chest",
      "lower_chest",
      "lats",
      "side_delt",
      "rear_delt",
      "triceps",
      "biceps",
      "abs",
      "glutes"
    ],
    movement_patterns: [
      "cable_fly",
      "cable_press",
      "lateral_raise",
      "triceps_pushdown",
      "cable_curl",
      "face_pull",
      "straight_arm_pulldown",
      "pallof_press",
      "glute_kickback"
    ],
    movement_family: [
      "horizontal_push",
      "fly",
      "shoulder_abduction",
      "elbow_extension",
      "elbow_flexion",
      "vertical_pull",
      "core",
      "hinge"
    ],
    angle: "mixed",
    is_unilateral: true,
    is_cable: true,
    stability_level: "medium",
    setup_difficulty: "medium",
    handles_grips: [
      "D handles",
      "rope",
      "straight bar",
      "EZ bar",
      "ankle cuff",
      "long strap"
    ],
    user_preference: "preferred",
    notes: "Primary cable station for press, fly, arm, delt, lat, and core work."
  }),
  eq({
    id: "eq-cable-crossover",
    name: "Cable Crossover Station",
    category: "Cable Station",
    equipment_type: "cable",
    load_type: "cable_stack",
    primary_muscles: ["chest", "rear_delt", "side_delt"],
    secondary_muscles: ["triceps", "biceps", "abs"],
    target_regions: [
      "upper_chest",
      "mid_chest",
      "lower_chest",
      "side_delt",
      "rear_delt",
      "abs"
    ],
    movement_patterns: ["cable_fly", "cross_body_fly", "face_pull", "wood_chop"],
    movement_family: ["fly", "shoulder_abduction", "core"],
    angle: "mixed",
    is_unilateral: true,
    is_cable: true,
    setup_difficulty: "medium",
    handles_grips: ["D handles", "rope", "long strap"]
  }),
  eq({
    id: "eq-assisted-dip",
    name: "Assisted Dip and Pull-Up Machine",
    category: "Assisted Bodyweight",
    equipment_type: "machine",
    load_type: "assisted",
    primary_muscles: ["triceps", "chest", "lats"],
    secondary_muscles: ["front_delt", "biceps"],
    target_regions: ["triceps", "lower_chest", "lats"],
    movement_patterns: ["assisted_dip", "assisted_pull_up"],
    movement_family: ["elbow_extension", "vertical_pull"],
    angle: "vertical",
    is_selectorized: true,
    fatigue_score: "medium_high",
    handles_grips: ["dip handles", "pull-up handles"]
  }),
  eq({
    id: "eq-lat-pulldown",
    name: "Lat Pulldown",
    category: "Lat Pulldown",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["lats"],
    secondary_muscles: ["biceps", "upper_back", "traps"],
    target_regions: ["lats", "upper_back", "biceps"],
    movement_patterns: ["wide_pulldown", "neutral_pulldown", "reverse_grip_pulldown"],
    movement_family: ["vertical_pull"],
    angle: "vertical",
    is_selectorized: true,
    handles_grips: ["wide bar", "MAG grip", "neutral handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-seated-cable-row",
    name: "Seated Cable Row",
    category: "Cable Row",
    equipment_type: "cable",
    load_type: "cable_stack",
    primary_muscles: ["mid_back", "lats"],
    secondary_muscles: ["biceps", "rear_delt", "traps"],
    target_regions: ["mid_back", "lats", "upper_back"],
    movement_patterns: ["seated_cable_row", "wide_cable_row", "neutral_cable_row"],
    movement_family: ["horizontal_pull"],
    angle: "horizontal",
    is_cable: true,
    handles_grips: ["close neutral handle", "wide bar", "single D handle"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-chest-supported-row",
    name: "Chest Supported Row Machine",
    category: "Row Machine",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["mid_back"],
    secondary_muscles: ["lats", "rear_delt", "biceps"],
    target_regions: ["mid_back", "upper_back", "lats"],
    movement_patterns: ["chest_supported_row", "neutral_row"],
    movement_family: ["horizontal_pull"],
    angle: "horizontal",
    is_selectorized: true,
    stability_level: "high",
    handles_grips: ["neutral handles", "pronated handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-prime-row",
    name: "Prime Row",
    brand: "Prime",
    category: "Row Machine",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["mid_back", "lats"],
    secondary_muscles: ["rear_delt", "biceps"],
    target_regions: ["mid_back", "lats", "upper_back"],
    movement_patterns: ["prime_row", "chest_supported_row"],
    movement_family: ["horizontal_pull"],
    angle: "horizontal",
    is_plate_loaded: true,
    handles_grips: ["multiple grip handles"],
    user_preference: "preferred",
    fatigue_score: "medium_high"
  }),
  eq({
    id: "eq-high-row",
    name: "High Row Machine",
    category: "High Row",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["lats", "upper_back"],
    secondary_muscles: ["biceps", "rear_delt"],
    target_regions: ["lats", "upper_back"],
    movement_patterns: ["high_row", "diagonal_row"],
    movement_family: ["vertical_pull", "horizontal_pull"],
    angle: "high_to_low",
    is_plate_loaded: true,
    handles_grips: ["neutral handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-low-row",
    name: "Low Row Machine",
    category: "Low Row",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["lats", "mid_back"],
    secondary_muscles: ["biceps", "rear_delt"],
    target_regions: ["lats", "mid_back"],
    movement_patterns: ["low_row", "diagonal_row"],
    movement_family: ["horizontal_pull"],
    angle: "low_to_high",
    is_plate_loaded: true,
    handles_grips: ["neutral handles"]
  }),
  eq({
    id: "eq-tbar-row",
    name: "T-Bar Row Machine",
    category: "Row Machine",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["mid_back"],
    secondary_muscles: ["lats", "traps", "biceps"],
    target_regions: ["mid_back", "upper_back", "lats"],
    movement_patterns: ["tbar_row"],
    movement_family: ["horizontal_pull"],
    angle: "horizontal",
    is_plate_loaded: true,
    fatigue_score: "high",
    handles_grips: ["neutral handles", "wide handles"]
  }),
  eq({
    id: "eq-nautilus-pullover",
    name: "Nautilus Pullover",
    brand: "Nautilus",
    category: "Pullover Machine",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["lats"],
    secondary_muscles: ["triceps"],
    target_regions: ["lats"],
    movement_patterns: ["machine_pullover", "lat_isolation"],
    movement_family: ["shoulder_extension"],
    angle: "vertical",
    is_selectorized: true,
    handles_grips: ["elbow pads", "overhead handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-rear-delt-machine",
    name: "Rear Delt Machine",
    category: "Rear Delt Fly",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["rear_delt"],
    secondary_muscles: ["traps", "upper_back"],
    target_regions: ["rear_delt", "upper_back"],
    movement_patterns: ["rear_delt_fly", "reverse_pec_deck"],
    movement_family: ["fly"],
    angle: "horizontal",
    is_selectorized: true,
    handles_grips: ["horizontal handles", "vertical handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-shoulder-press",
    name: "Shoulder Press Machine",
    category: "Shoulder Press",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["front_delt"],
    secondary_muscles: ["side_delt", "triceps"],
    target_regions: ["front_delt", "side_delt", "triceps"],
    movement_patterns: ["machine_shoulder_press", "neutral_shoulder_press"],
    movement_family: ["vertical_push"],
    angle: "vertical",
    is_selectorized: true,
    handles_grips: ["neutral handles", "pronated handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-lateral-raise",
    name: "Lateral Raise Machine",
    category: "Lateral Raise",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["side_delt"],
    secondary_muscles: ["traps"],
    target_regions: ["side_delt"],
    movement_patterns: ["machine_lateral_raise"],
    movement_family: ["shoulder_abduction"],
    angle: "vertical",
    is_selectorized: true,
    handles_grips: ["forearm pads"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-smith-machine",
    name: "Smith Machine",
    category: "Smith Machine",
    equipment_type: "smith_machine",
    load_type: "free_weight",
    primary_muscles: ["chest", "quads", "glutes", "traps"],
    secondary_muscles: ["triceps", "front_delt", "hamstrings"],
    target_regions: ["upper_chest", "mid_chest", "quads", "glutes", "traps"],
    movement_patterns: [
      "smith_incline_press",
      "smith_decline_press",
      "smith_squat",
      "smith_split_squat",
      "smith_upright_row"
    ],
    movement_family: [
      "horizontal_push",
      "squat",
      "vertical_push",
      "shoulder_abduction"
    ],
    angle: "mixed",
    is_plate_loaded: true,
    stability_level: "medium",
    fatigue_score: "high",
    setup_difficulty: "medium",
    handles_grips: ["fixed bar"],
    user_preference: "avoid"
  }),
  eq({
    id: "eq-hack-squat",
    name: "Hack Squat Machine",
    category: "Squat Machine",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["quads"],
    secondary_muscles: ["glutes", "hamstrings"],
    target_regions: ["quads", "glutes"],
    movement_patterns: ["hack_squat"],
    movement_family: ["squat"],
    angle: "vertical",
    is_plate_loaded: true,
    fatigue_score: "high",
    handles_grips: ["shoulder pads"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-v-squat",
    name: "V Squat Machine",
    category: "Squat Machine",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["quads", "glutes"],
    secondary_muscles: ["hamstrings"],
    target_regions: ["quads", "glutes"],
    movement_patterns: ["v_squat"],
    movement_family: ["squat"],
    angle: "vertical",
    is_plate_loaded: true,
    fatigue_score: "high",
    handles_grips: ["shoulder pads"]
  }),
  eq({
    id: "eq-leg-press-45",
    name: "45 Degree Leg Press",
    category: "Leg Press",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["quads"],
    secondary_muscles: ["glutes", "hamstrings", "calves"],
    target_regions: ["quads", "glutes", "calves"],
    movement_patterns: ["leg_press_45", "calf_press"],
    movement_family: ["squat"],
    angle: "incline",
    is_plate_loaded: true,
    fatigue_score: "high",
    handles_grips: ["side handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-horizontal-leg-press",
    name: "Horizontal Leg Press",
    category: "Leg Press",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["quads"],
    secondary_muscles: ["glutes", "hamstrings", "calves"],
    target_regions: ["quads", "glutes", "calves"],
    movement_patterns: ["horizontal_leg_press"],
    movement_family: ["squat"],
    angle: "horizontal",
    is_selectorized: true,
    fatigue_score: "medium_high",
    handles_grips: ["seat handles"]
  }),
  eq({
    id: "eq-leg-extension",
    name: "Leg Extension",
    category: "Leg Extension",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["quads"],
    target_regions: ["quads"],
    movement_patterns: ["leg_extension", "single_leg_extension"],
    movement_family: ["knee_extension"],
    is_selectorized: true,
    handles_grips: ["seat handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-seated-leg-curl",
    name: "Seated Leg Curl",
    category: "Leg Curl",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["hamstrings"],
    secondary_muscles: ["calves"],
    target_regions: ["hamstrings"],
    movement_patterns: ["seated_leg_curl", "single_leg_curl"],
    movement_family: ["knee_flexion"],
    is_selectorized: true,
    handles_grips: ["seat handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-lying-leg-curl",
    name: "Lying Leg Curl",
    category: "Leg Curl",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["hamstrings"],
    secondary_muscles: ["calves"],
    target_regions: ["hamstrings"],
    movement_patterns: ["lying_leg_curl"],
    movement_family: ["knee_flexion"],
    angle: "horizontal",
    is_selectorized: true,
    handles_grips: ["front handles"]
  }),
  eq({
    id: "eq-hip-abduction",
    name: "Hip Abduction Machine",
    category: "Hip Abduction",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["abductors", "glutes"],
    target_regions: ["abductors", "glutes"],
    movement_patterns: ["hip_abduction"],
    movement_family: ["hip_abduction"],
    is_selectorized: true,
    handles_grips: ["seat handles"]
  }),
  eq({
    id: "eq-hip-adduction",
    name: "Hip Adduction Machine",
    category: "Hip Adduction",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["adductors"],
    target_regions: ["adductors"],
    movement_patterns: ["hip_adduction"],
    movement_family: ["hip_adduction"],
    is_selectorized: true,
    handles_grips: ["seat handles"]
  }),
  eq({
    id: "eq-standing-calf",
    name: "Standing Calf Raise Machine",
    category: "Calf Raise",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["calves"],
    target_regions: ["calves"],
    movement_patterns: ["standing_calf_raise"],
    movement_family: ["squat"],
    angle: "vertical",
    is_plate_loaded: true,
    fatigue_score: "medium_high",
    handles_grips: ["shoulder pads"]
  }),
  eq({
    id: "eq-seated-calf",
    name: "Seated Calf Raise Machine",
    category: "Calf Raise",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["calves"],
    target_regions: ["calves"],
    movement_patterns: ["seated_calf_raise"],
    movement_family: ["squat"],
    angle: "horizontal",
    is_plate_loaded: true,
    handles_grips: ["knee pad"]
  }),
  eq({
    id: "eq-preacher-curl",
    name: "Preacher Curl Machine",
    category: "Curl Machine",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["biceps"],
    secondary_muscles: ["forearms"],
    target_regions: ["biceps"],
    movement_patterns: ["preacher_curl"],
    movement_family: ["elbow_flexion"],
    is_selectorized: true,
    handles_grips: ["EZ handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-triceps-extension",
    name: "Triceps Extension Machine",
    category: "Triceps Extension",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["triceps"],
    target_regions: ["triceps"],
    movement_patterns: ["machine_triceps_extension"],
    movement_family: ["elbow_extension"],
    is_selectorized: true,
    handles_grips: ["neutral handles"],
    user_preference: "preferred"
  }),
  eq({
    id: "eq-dip-machine",
    name: "Dip Machine",
    category: "Dip Machine",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["triceps", "chest"],
    secondary_muscles: ["front_delt"],
    target_regions: ["triceps", "lower_chest"],
    movement_patterns: ["seated_dip", "machine_dip"],
    movement_family: ["elbow_extension", "horizontal_push"],
    is_selectorized: true,
    fatigue_score: "medium_high",
    handles_grips: ["dip handles"]
  }),
  eq({
    id: "eq-glute-drive",
    name: "Glute Drive Machine",
    category: "Glute Drive",
    equipment_type: "machine",
    load_type: "plate_loaded",
    primary_muscles: ["glutes"],
    secondary_muscles: ["hamstrings"],
    target_regions: ["glutes", "hamstrings"],
    movement_patterns: ["glute_drive", "hip_thrust"],
    movement_family: ["hinge"],
    angle: "horizontal",
    is_plate_loaded: true,
    fatigue_score: "medium_high",
    handles_grips: ["lap belt", "side handles"]
  }),
  eq({
    id: "eq-back-extension",
    name: "Back Extension Bench",
    category: "Back Extension",
    equipment_type: "machine",
    load_type: "bodyweight",
    primary_muscles: ["lower_back", "glutes"],
    secondary_muscles: ["hamstrings"],
    target_regions: ["lower_back", "glutes", "hamstrings"],
    movement_patterns: ["back_extension", "glute_bias_back_extension"],
    movement_family: ["hinge"],
    angle: "decline",
    stability_level: "medium",
    fatigue_score: "medium",
    handles_grips: ["hip pad"]
  }),
  eq({
    id: "eq-ab-crunch",
    name: "Ab Crunch Machine",
    category: "Core Machine",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["abs"],
    secondary_muscles: ["obliques"],
    target_regions: ["abs"],
    movement_patterns: ["machine_crunch"],
    movement_family: ["core"],
    is_selectorized: true,
    handles_grips: ["overhead handles"]
  }),
  eq({
    id: "eq-rotary-torso",
    name: "Rotary Torso Machine",
    category: "Core Machine",
    equipment_type: "machine",
    load_type: "selectorized",
    primary_muscles: ["obliques", "abs"],
    target_regions: ["obliques", "abs"],
    movement_patterns: ["rotary_torso"],
    movement_family: ["core"],
    angle: "rotational",
    is_selectorized: true,
    handles_grips: ["torso pads", "hand grips"]
  }),
  eq({
    id: "eq-treadmill",
    name: "Treadmill",
    category: "Cardio",
    equipment_type: "cardio",
    load_type: "unknown",
    primary_muscles: ["cardio", "calves", "quads"],
    secondary_muscles: ["glutes", "hamstrings"],
    target_regions: ["cardio", "calves"],
    movement_patterns: ["incline_walk", "run"],
    movement_family: ["cardio"],
    angle: "incline",
    fatigue_score: "medium",
    handles_grips: ["side rails"]
  }),
  eq({
    id: "eq-stair-climber",
    name: "Stair Climber",
    category: "Cardio",
    equipment_type: "cardio",
    load_type: "unknown",
    primary_muscles: ["cardio", "glutes", "quads"],
    secondary_muscles: ["calves", "hamstrings"],
    target_regions: ["cardio", "glutes", "quads"],
    movement_patterns: ["stair_climb"],
    movement_family: ["cardio"],
    angle: "vertical",
    fatigue_score: "medium_high",
    handles_grips: ["side rails"]
  }),
  eq({
    id: "eq-stationary-bike",
    name: "Stationary Bike",
    category: "Cardio",
    equipment_type: "cardio",
    load_type: "unknown",
    primary_muscles: ["cardio", "quads"],
    secondary_muscles: ["hamstrings", "glutes", "calves"],
    target_regions: ["cardio", "quads"],
    movement_patterns: ["bike_zone_2", "bike_intervals"],
    movement_family: ["cardio"],
    angle: "horizontal",
    fatigue_score: "low",
    handles_grips: ["bike handles"]
  }),
  eq({
    id: "eq-cable-attachments",
    name: "Cable Attachment Set",
    category: "Accessory",
    equipment_type: "accessory",
    load_type: "unknown",
    primary_muscles: ["chest", "lats", "triceps", "biceps", "side_delt"],
    secondary_muscles: ["rear_delt", "abs"],
    target_regions: [
      "upper_chest",
      "mid_chest",
      "lower_chest",
      "lats",
      "triceps",
      "biceps",
      "side_delt",
      "rear_delt",
      "abs"
    ],
    movement_patterns: ["attachment_variation"],
    movement_family: [
      "fly",
      "vertical_pull",
      "horizontal_pull",
      "elbow_extension",
      "elbow_flexion",
      "shoulder_abduction",
      "core"
    ],
    angle: "mixed",
    handles_grips: ["rope", "straight bar", "EZ bar", "D handles", "ankle cuff"],
    notes: "Accessory record for future schema support; cable exercises are tied to cable stations."
  }),
  eq({
    id: "eq-dumbbell-set",
    name: "Dumbbell Set",
    category: "Free Weight",
    equipment_type: "dumbbell",
    load_type: "free_weight",
    primary_muscles: ["chest", "side_delt", "rear_delt", "biceps", "triceps", "quads", "hamstrings", "glutes"],
    target_regions: ["mid_chest", "upper_chest", "side_delt", "rear_delt", "biceps", "triceps", "quads", "hamstrings", "glutes"],
    movement_patterns: ["dumbbell_press", "dumbbell_row", "dumbbell_raise", "dumbbell_curl", "dumbbell_lunge", "dumbbell_rdl"],
    movement_family: ["horizontal_push", "horizontal_pull", "shoulder_abduction", "elbow_flexion", "elbow_extension", "squat", "hinge"],
    angle: "mixed",
    is_unilateral: true,
    fatigue_score: "medium",
    stability_level: "medium",
    setup_difficulty: "low",
    handles_grips: ["dumbbell handles"]
  }),
  eq({
    id: "eq-olympic-barbell",
    name: "Olympic Barbell",
    category: "Free Weight",
    equipment_type: "barbell",
    load_type: "free_weight",
    primary_muscles: ["chest", "front_delt", "upper_back", "quads", "hamstrings", "glutes", "triceps"],
    secondary_muscles: ["abs", "lower_back"],
    target_regions: ["mid_chest", "upper_chest", "front_delt", "upper_back", "quads", "hamstrings", "glutes", "triceps"],
    movement_patterns: ["barbell_press", "barbell_row", "back_squat", "front_squat", "romanian_deadlift", "hip_thrust"],
    movement_family: ["horizontal_push", "vertical_push", "horizontal_pull", "squat", "hinge", "elbow_extension"],
    angle: "mixed",
    is_plate_loaded: true,
    fatigue_score: "high",
    stability_level: "high",
    setup_difficulty: "medium",
    handles_grips: ["barbell"]
  }),
  eq({
    id: "eq-ez-curl-bar",
    name: "EZ Curl Bar",
    category: "Free Weight",
    equipment_type: "barbell",
    load_type: "free_weight",
    primary_muscles: ["biceps", "triceps", "traps"],
    target_regions: ["biceps", "triceps", "traps"],
    movement_patterns: ["ez_bar_curl", "skull_crusher", "upright_row"],
    movement_family: ["elbow_flexion", "elbow_extension", "shoulder_abduction"],
    fatigue_score: "medium",
    stability_level: "medium",
    setup_difficulty: "low",
    handles_grips: ["angled bar"]
  }),
  eq({
    id: "eq-flat-bench",
    name: "Flat Bench",
    category: "Bench",
    equipment_type: "accessory",
    load_type: "unknown",
    primary_muscles: ["chest", "upper_back", "triceps"],
    target_regions: ["mid_chest", "upper_back", "triceps"],
    movement_patterns: ["bench_support"],
    movement_family: ["horizontal_push", "horizontal_pull", "elbow_extension"],
    angle: "flat",
    stability_level: "low"
  }),
  eq({
    id: "eq-adjustable-bench",
    name: "Adjustable Bench",
    category: "Bench",
    equipment_type: "accessory",
    load_type: "unknown",
    primary_muscles: ["chest", "upper_back", "front_delt", "biceps"],
    target_regions: ["upper_chest", "mid_chest", "upper_back", "front_delt", "biceps"],
    movement_patterns: ["incline_bench_support", "flat_bench_support"],
    movement_family: ["horizontal_push", "horizontal_pull", "vertical_push", "elbow_flexion"],
    angle: "mixed",
    stability_level: "low"
  }),
  eq({
    id: "eq-power-rack",
    name: "Power Rack",
    category: "Rack",
    equipment_type: "accessory",
    load_type: "unknown",
    primary_muscles: ["chest", "quads", "hamstrings", "glutes", "front_delt"],
    target_regions: ["mid_chest", "quads", "hamstrings", "glutes", "front_delt"],
    movement_patterns: ["rack_press", "rack_squat", "rack_overhead_press"],
    movement_family: ["horizontal_push", "squat", "vertical_push"],
    setup_difficulty: "medium"
  }),
  eq({
    id: "eq-squat-rack",
    name: "Squat Rack",
    category: "Rack",
    equipment_type: "accessory",
    load_type: "unknown",
    primary_muscles: ["quads", "hamstrings", "glutes"],
    target_regions: ["quads", "hamstrings", "glutes"],
    movement_patterns: ["rack_squat", "rack_lunge"],
    movement_family: ["squat", "hinge"],
    setup_difficulty: "medium"
  }),
  eq({
    id: "eq-bench-press-rack",
    name: "Bench Press Rack",
    category: "Rack",
    equipment_type: "accessory",
    load_type: "unknown",
    primary_muscles: ["chest", "triceps", "front_delt"],
    target_regions: ["mid_chest", "upper_chest", "triceps", "front_delt"],
    movement_patterns: ["bench_press_rack"],
    movement_family: ["horizontal_push"],
    setup_difficulty: "medium"
  })
];

export function getEquipmentById(id: string, equipment = equipmentCatalog) {
  return equipment.find((item) => item.id === id);
}
