import type { Exercise } from "@/lib/types";

const exerciseDefaults: Pick<
  Exercise,
  | "secondary_muscles"
  | "compatible_equipment_categories"
  | "equipment_type_preference"
  | "default_sets"
  | "default_rep_min"
  | "default_rep_max"
  | "default_rest_seconds"
  | "fatigue_score"
  | "technical_difficulty"
  | "progression_type"
  | "notes"
> = {
  secondary_muscles: [],
  compatible_equipment_categories: [],
  equipment_type_preference: ["machine", "cable"],
  default_sets: 3,
  default_rep_min: 8,
  default_rep_max: 12,
  default_rest_seconds: 90,
  fatigue_score: "medium",
  technical_difficulty: "medium",
  progression_type: "load",
  notes: ""
};

type ExerciseSeed = Omit<Exercise, keyof typeof exerciseDefaults> &
  Partial<typeof exerciseDefaults>;

function ex(input: ExerciseSeed): Exercise {
  return { ...exerciseDefaults, ...input };
}

export const exerciseCatalog: Exercise[] = [
  ex({
    id: "ex-hs-decline-press",
    name: "Hammer Strength Iso-Lateral Decline Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt"],
    target_region: "lower_chest",
    movement_pattern: "decline_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-hs-decline-press"],
    compatible_equipment_categories: ["Chest Press"],
    default_weight_lbs: 180,
    fatigue_score: "medium_high",
    notes: "Primary machine option for lower chest pressing."
  }),
  ex({
    id: "ex-incline-chest-press",
    name: "Incline Chest Press Machine",
    primary_muscle: "chest",
    secondary_muscles: ["front_delt", "triceps"],
    target_region: "upper_chest",
    movement_pattern: "incline_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-incline-chest-press"],
    compatible_equipment_categories: ["Chest Press"],
    default_weight_lbs: 115,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-plate-loaded-chest-press",
    name: "Plate Loaded Chest Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt"],
    target_region: "mid_chest",
    movement_pattern: "flat_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-plate-loaded-chest-press"],
    compatible_equipment_categories: ["Chest Press"],
    default_weight_lbs: 190,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-selectorized-chest-press",
    name: "Selectorized Chest Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt"],
    target_region: "mid_chest",
    movement_pattern: "flat_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-selectorized-chest-press"],
    compatible_equipment_categories: ["Chest Press"],
    default_weight_lbs: 125
  }),
  ex({
    id: "ex-close-grip-machine-chest-press",
    name: "Close Grip Machine Chest Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt"],
    target_region: "mid_chest",
    movement_pattern: "close_grip_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-selectorized-chest-press"],
    compatible_equipment_categories: ["Chest Press"],
    default_weight_lbs: 105
  }),
  ex({
    id: "ex-pec-deck-fly",
    name: "Pec Deck Fly",
    primary_muscle: "chest",
    secondary_muscles: ["front_delt"],
    target_region: "mid_chest",
    movement_pattern: "pec_deck_fly",
    movement_family: "fly",
    required_equipment_ids: ["eq-pec-deck"],
    compatible_equipment_categories: ["Chest Fly"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 95
  }),
  ex({
    id: "ex-cable-high-low-fly",
    name: "Cable High-to-Low Fly",
    primary_muscle: "chest",
    secondary_muscles: ["front_delt"],
    target_region: "lower_chest",
    movement_pattern: "high_to_low_cable_fly",
    movement_family: "fly",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 45
  }),
  ex({
    id: "ex-cable-low-high-fly",
    name: "Cable Low-to-High Fly",
    primary_muscle: "chest",
    secondary_muscles: ["front_delt"],
    target_region: "upper_chest",
    movement_pattern: "low_to_high_cable_fly",
    movement_family: "fly",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 35
  }),
  ex({
    id: "ex-cable-standing-chest-press",
    name: "Standing Cable Chest Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt", "abs"],
    target_region: "mid_chest",
    movement_pattern: "cable_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 60
  }),
  ex({
    id: "ex-assisted-dip-chest",
    name: "Assisted Dip - Chest Bias",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt"],
    target_region: "lower_chest",
    movement_pattern: "assisted_dip",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-assisted-dip"],
    compatible_equipment_categories: ["Assisted Bodyweight"],
    default_weight_lbs: 70,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-smith-incline-press",
    name: "Smith Machine Incline Press",
    primary_muscle: "chest",
    secondary_muscles: ["front_delt", "triceps"],
    target_region: "upper_chest",
    movement_pattern: "smith_incline_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-smith-machine"],
    compatible_equipment_categories: ["Smith Machine"],
    equipment_type_preference: ["smith_machine"],
    default_weight_lbs: 135,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-smith-decline-press",
    name: "Smith Machine Decline Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt"],
    target_region: "lower_chest",
    movement_pattern: "smith_decline_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-smith-machine"],
    compatible_equipment_categories: ["Smith Machine"],
    equipment_type_preference: ["smith_machine"],
    default_weight_lbs: 145,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-single-arm-cable-press",
    name: "Single Arm Cable Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt", "abs"],
    target_region: "mid_chest",
    movement_pattern: "single_arm_cable_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 35
  }),
  ex({
    id: "ex-cross-body-cable-fly",
    name: "Cross Body Cable Fly",
    primary_muscle: "chest",
    secondary_muscles: ["front_delt"],
    target_region: "mid_chest",
    movement_pattern: "cross_body_fly",
    movement_family: "fly",
    required_equipment_ids: ["eq-cable-crossover"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 12,
    default_rep_max: 16,
    default_weight_lbs: 25
  }),
  ex({
    id: "ex-wide-lat-pulldown",
    name: "Wide Grip Lat Pulldown",
    primary_muscle: "lats",
    secondary_muscles: ["biceps", "upper_back"],
    target_region: "lats",
    movement_pattern: "wide_pulldown",
    movement_family: "vertical_pull",
    required_equipment_ids: ["eq-lat-pulldown"],
    compatible_equipment_categories: ["Lat Pulldown"],
    default_weight_lbs: 130
  }),
  ex({
    id: "ex-neutral-lat-pulldown",
    name: "Neutral Grip Lat Pulldown",
    primary_muscle: "lats",
    secondary_muscles: ["biceps", "upper_back"],
    target_region: "lats",
    movement_pattern: "neutral_pulldown",
    movement_family: "vertical_pull",
    required_equipment_ids: ["eq-lat-pulldown"],
    compatible_equipment_categories: ["Lat Pulldown"],
    default_weight_lbs: 125
  }),
  ex({
    id: "ex-reverse-grip-pulldown",
    name: "Reverse Grip Pulldown",
    primary_muscle: "lats",
    secondary_muscles: ["biceps", "mid_back"],
    target_region: "lats",
    movement_pattern: "reverse_grip_pulldown",
    movement_family: "vertical_pull",
    required_equipment_ids: ["eq-lat-pulldown"],
    compatible_equipment_categories: ["Lat Pulldown"],
    default_weight_lbs: 115
  }),
  ex({
    id: "ex-seated-cable-row-neutral",
    name: "Seated Cable Row - Neutral Grip",
    primary_muscle: "mid_back",
    secondary_muscles: ["lats", "biceps", "rear_delt"],
    target_region: "mid_back",
    movement_pattern: "neutral_cable_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-seated-cable-row"],
    compatible_equipment_categories: ["Cable Row"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 125
  }),
  ex({
    id: "ex-seated-cable-row-wide",
    name: "Seated Cable Row - Wide Grip",
    primary_muscle: "upper_back",
    secondary_muscles: ["rear_delt", "biceps", "mid_back"],
    target_region: "upper_back",
    movement_pattern: "wide_cable_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-seated-cable-row"],
    compatible_equipment_categories: ["Cable Row"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 110
  }),
  ex({
    id: "ex-chest-supported-row-neutral",
    name: "Chest Supported Row - Neutral Grip",
    primary_muscle: "mid_back",
    secondary_muscles: ["lats", "rear_delt", "biceps"],
    target_region: "mid_back",
    movement_pattern: "chest_supported_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-chest-supported-row"],
    compatible_equipment_categories: ["Row Machine"],
    default_weight_lbs: 120
  }),
  ex({
    id: "ex-prime-row-pronated",
    name: "Prime Row - Pronated",
    primary_muscle: "mid_back",
    secondary_muscles: ["lats", "rear_delt", "biceps"],
    target_region: "mid_back",
    movement_pattern: "prime_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-prime-row"],
    compatible_equipment_categories: ["Row Machine"],
    default_weight_lbs: 160,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-prime-row-lat-bias",
    name: "Prime Row - Lat Bias",
    primary_muscle: "lats",
    secondary_muscles: ["mid_back", "biceps"],
    target_region: "lats",
    movement_pattern: "prime_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-prime-row"],
    compatible_equipment_categories: ["Row Machine"],
    default_weight_lbs: 145
  }),
  ex({
    id: "ex-high-row-machine",
    name: "High Row Machine",
    primary_muscle: "lats",
    secondary_muscles: ["upper_back", "biceps"],
    target_region: "lats",
    movement_pattern: "high_row",
    movement_family: "vertical_pull",
    required_equipment_ids: ["eq-high-row"],
    compatible_equipment_categories: ["High Row"],
    default_weight_lbs: 170,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-high-row-upper-back",
    name: "High Row Machine - Upper Back Bias",
    primary_muscle: "upper_back",
    secondary_muscles: ["lats", "rear_delt", "biceps"],
    target_region: "upper_back",
    movement_pattern: "diagonal_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-high-row"],
    compatible_equipment_categories: ["High Row"],
    default_weight_lbs: 150
  }),
  ex({
    id: "ex-low-row-machine",
    name: "Low Row Machine",
    primary_muscle: "lats",
    secondary_muscles: ["mid_back", "biceps"],
    target_region: "lats",
    movement_pattern: "low_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-low-row"],
    compatible_equipment_categories: ["Low Row"],
    default_weight_lbs: 165
  }),
  ex({
    id: "ex-tbar-row-machine",
    name: "T-Bar Row Machine",
    primary_muscle: "mid_back",
    secondary_muscles: ["lats", "traps", "biceps"],
    target_region: "mid_back",
    movement_pattern: "tbar_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-tbar-row"],
    compatible_equipment_categories: ["Row Machine"],
    default_weight_lbs: 135,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-nautilus-pullover",
    name: "Nautilus Pullover",
    primary_muscle: "lats",
    secondary_muscles: ["triceps"],
    target_region: "lats",
    movement_pattern: "machine_pullover",
    movement_family: "shoulder_extension",
    required_equipment_ids: ["eq-nautilus-pullover"],
    compatible_equipment_categories: ["Pullover Machine"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 95
  }),
  ex({
    id: "ex-straight-arm-cable-pulldown",
    name: "Straight Arm Cable Pulldown",
    primary_muscle: "lats",
    secondary_muscles: ["triceps"],
    target_region: "lats",
    movement_pattern: "straight_arm_pulldown",
    movement_family: "shoulder_extension",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 55
  }),
  ex({
    id: "ex-kneeling-cable-pullover",
    name: "Kneeling Cable Pullover",
    primary_muscle: "lats",
    secondary_muscles: ["triceps", "abs"],
    target_region: "lats",
    movement_pattern: "cable_pullover",
    movement_family: "shoulder_extension",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 50
  }),
  ex({
    id: "ex-rear-delt-machine",
    name: "Rear Delt Machine Fly",
    primary_muscle: "rear_delt",
    secondary_muscles: ["traps", "upper_back"],
    target_region: "rear_delt",
    movement_pattern: "rear_delt_fly",
    movement_family: "fly",
    required_equipment_ids: ["eq-rear-delt-machine"],
    compatible_equipment_categories: ["Rear Delt Fly"],
    default_rep_min: 12,
    default_rep_max: 18,
    default_weight_lbs: 75
  }),
  ex({
    id: "ex-cable-face-pull",
    name: "Cable Face Pull",
    primary_muscle: "rear_delt",
    secondary_muscles: ["traps", "upper_back"],
    target_region: "rear_delt",
    movement_pattern: "face_pull",
    movement_family: "fly",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 12,
    default_rep_max: 18,
    default_weight_lbs: 50
  }),
  ex({
    id: "ex-single-arm-cable-row",
    name: "Single Arm Cable Row",
    primary_muscle: "mid_back",
    secondary_muscles: ["lats", "biceps", "rear_delt"],
    target_region: "mid_back",
    movement_pattern: "single_arm_cable_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 55
  }),
  ex({
    id: "ex-machine-shoulder-press",
    name: "Machine Shoulder Press",
    primary_muscle: "front_delt",
    secondary_muscles: ["side_delt", "triceps"],
    target_region: "front_delt",
    movement_pattern: "machine_shoulder_press",
    movement_family: "vertical_push",
    required_equipment_ids: ["eq-shoulder-press"],
    compatible_equipment_categories: ["Shoulder Press"],
    default_weight_lbs: 95,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-neutral-shoulder-press",
    name: "Neutral Grip Shoulder Press Machine",
    primary_muscle: "front_delt",
    secondary_muscles: ["side_delt", "triceps"],
    target_region: "front_delt",
    movement_pattern: "neutral_shoulder_press",
    movement_family: "vertical_push",
    required_equipment_ids: ["eq-shoulder-press"],
    compatible_equipment_categories: ["Shoulder Press"],
    default_weight_lbs: 90
  }),
  ex({
    id: "ex-machine-lateral-raise",
    name: "Lateral Raise Machine",
    primary_muscle: "side_delt",
    secondary_muscles: ["traps"],
    target_region: "side_delt",
    movement_pattern: "machine_lateral_raise",
    movement_family: "shoulder_abduction",
    required_equipment_ids: ["eq-lateral-raise"],
    compatible_equipment_categories: ["Lateral Raise"],
    default_rep_min: 12,
    default_rep_max: 18,
    default_weight_lbs: 55
  }),
  ex({
    id: "ex-cable-lateral-raise",
    name: "Cable Lateral Raise",
    primary_muscle: "side_delt",
    secondary_muscles: ["traps"],
    target_region: "side_delt",
    movement_pattern: "cable_lateral_raise",
    movement_family: "shoulder_abduction",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 12,
    default_rep_max: 20,
    default_weight_lbs: 20
  }),
  ex({
    id: "ex-lean-away-cable-lateral-raise",
    name: "Lean Away Cable Lateral Raise",
    primary_muscle: "side_delt",
    secondary_muscles: ["traps"],
    target_region: "side_delt",
    movement_pattern: "lean_away_cable_lateral_raise",
    movement_family: "shoulder_abduction",
    required_equipment_ids: ["eq-cable-crossover"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 12,
    default_rep_max: 20,
    default_weight_lbs: 17.5
  }),
  ex({
    id: "ex-rear-delt-cable-fly",
    name: "Rear Delt Cable Fly",
    primary_muscle: "rear_delt",
    secondary_muscles: ["upper_back", "traps"],
    target_region: "rear_delt",
    movement_pattern: "rear_delt_cable_fly",
    movement_family: "fly",
    required_equipment_ids: ["eq-cable-crossover"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 12,
    default_rep_max: 18,
    default_weight_lbs: 20
  }),
  ex({
    id: "ex-cable-front-raise",
    name: "Cable Front Raise",
    primary_muscle: "front_delt",
    secondary_muscles: ["chest"],
    target_region: "front_delt",
    movement_pattern: "cable_front_raise",
    movement_family: "shoulder_abduction",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 25
  }),
  ex({
    id: "ex-cable-y-raise",
    name: "Cable Y Raise",
    primary_muscle: "side_delt",
    secondary_muscles: ["rear_delt", "traps"],
    target_region: "side_delt",
    movement_pattern: "cable_y_raise",
    movement_family: "shoulder_abduction",
    required_equipment_ids: ["eq-cable-crossover"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 12,
    default_rep_max: 18,
    default_weight_lbs: 15
  }),
  ex({
    id: "ex-smith-upright-row",
    name: "Smith Machine Upright Row",
    primary_muscle: "side_delt",
    secondary_muscles: ["traps", "biceps"],
    target_region: "side_delt",
    movement_pattern: "smith_upright_row",
    movement_family: "shoulder_abduction",
    required_equipment_ids: ["eq-smith-machine"],
    compatible_equipment_categories: ["Smith Machine"],
    equipment_type_preference: ["smith_machine"],
    default_weight_lbs: 75,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-cable-external-rotation",
    name: "Cable External Rotation",
    primary_muscle: "rear_delt",
    secondary_muscles: ["upper_back"],
    target_region: "rear_delt",
    movement_pattern: "external_rotation",
    movement_family: "fly",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_sets: 2,
    default_rep_min: 12,
    default_rep_max: 20,
    default_weight_lbs: 10,
    fatigue_score: "low",
    technical_difficulty: "low"
  }),
  ex({
    id: "ex-machine-shoulder-press-high-rep",
    name: "Machine Shoulder Press - High Rep",
    primary_muscle: "front_delt",
    secondary_muscles: ["side_delt", "triceps"],
    target_region: "front_delt",
    movement_pattern: "machine_shoulder_press",
    movement_family: "vertical_push",
    required_equipment_ids: ["eq-shoulder-press"],
    compatible_equipment_categories: ["Shoulder Press"],
    default_rep_min: 12,
    default_rep_max: 15,
    default_weight_lbs: 75
  }),
  ex({
    id: "ex-hack-squat",
    name: "Hack Squat",
    primary_muscle: "quads",
    secondary_muscles: ["glutes", "hamstrings"],
    target_region: "quads",
    movement_pattern: "hack_squat",
    movement_family: "squat",
    required_equipment_ids: ["eq-hack-squat"],
    compatible_equipment_categories: ["Squat Machine"],
    default_weight_lbs: 230,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-v-squat",
    name: "V Squat",
    primary_muscle: "quads",
    secondary_muscles: ["glutes", "hamstrings"],
    target_region: "quads",
    movement_pattern: "v_squat",
    movement_family: "squat",
    required_equipment_ids: ["eq-v-squat"],
    compatible_equipment_categories: ["Squat Machine"],
    default_weight_lbs: 220,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-leg-press-45",
    name: "45 Degree Leg Press",
    primary_muscle: "quads",
    secondary_muscles: ["glutes", "hamstrings"],
    target_region: "quads",
    movement_pattern: "leg_press_45",
    movement_family: "squat",
    required_equipment_ids: ["eq-leg-press-45"],
    compatible_equipment_categories: ["Leg Press"],
    default_weight_lbs: 360,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-horizontal-leg-press",
    name: "Horizontal Leg Press",
    primary_muscle: "quads",
    secondary_muscles: ["glutes", "hamstrings"],
    target_region: "quads",
    movement_pattern: "horizontal_leg_press",
    movement_family: "squat",
    required_equipment_ids: ["eq-horizontal-leg-press"],
    compatible_equipment_categories: ["Leg Press"],
    default_weight_lbs: 190,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-leg-extension",
    name: "Leg Extension",
    primary_muscle: "quads",
    target_region: "quads",
    movement_pattern: "leg_extension",
    movement_family: "knee_extension",
    required_equipment_ids: ["eq-leg-extension"],
    compatible_equipment_categories: ["Leg Extension"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 115
  }),
  ex({
    id: "ex-single-leg-extension",
    name: "Single Leg Extension",
    primary_muscle: "quads",
    target_region: "quads",
    movement_pattern: "single_leg_extension",
    movement_family: "knee_extension",
    required_equipment_ids: ["eq-leg-extension"],
    compatible_equipment_categories: ["Leg Extension"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 55
  }),
  ex({
    id: "ex-seated-leg-curl",
    name: "Seated Leg Curl",
    primary_muscle: "hamstrings",
    secondary_muscles: ["calves"],
    target_region: "hamstrings",
    movement_pattern: "seated_leg_curl",
    movement_family: "knee_flexion",
    required_equipment_ids: ["eq-seated-leg-curl"],
    compatible_equipment_categories: ["Leg Curl"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 100
  }),
  ex({
    id: "ex-lying-leg-curl",
    name: "Lying Leg Curl",
    primary_muscle: "hamstrings",
    secondary_muscles: ["calves"],
    target_region: "hamstrings",
    movement_pattern: "lying_leg_curl",
    movement_family: "knee_flexion",
    required_equipment_ids: ["eq-lying-leg-curl"],
    compatible_equipment_categories: ["Leg Curl"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 90
  }),
  ex({
    id: "ex-single-leg-seated-curl",
    name: "Single Leg Seated Curl",
    primary_muscle: "hamstrings",
    secondary_muscles: ["calves"],
    target_region: "hamstrings",
    movement_pattern: "single_leg_curl",
    movement_family: "knee_flexion",
    required_equipment_ids: ["eq-seated-leg-curl"],
    compatible_equipment_categories: ["Leg Curl"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 45
  }),
  ex({
    id: "ex-hip-abduction",
    name: "Hip Abduction Machine",
    primary_muscle: "abductors",
    secondary_muscles: ["glutes"],
    target_region: "abductors",
    movement_pattern: "hip_abduction",
    movement_family: "hip_abduction",
    required_equipment_ids: ["eq-hip-abduction"],
    compatible_equipment_categories: ["Hip Abduction"],
    default_rep_min: 12,
    default_rep_max: 20,
    default_weight_lbs: 105
  }),
  ex({
    id: "ex-hip-adduction",
    name: "Hip Adduction Machine",
    primary_muscle: "adductors",
    target_region: "adductors",
    movement_pattern: "hip_adduction",
    movement_family: "hip_adduction",
    required_equipment_ids: ["eq-hip-adduction"],
    compatible_equipment_categories: ["Hip Adduction"],
    default_rep_min: 12,
    default_rep_max: 20,
    default_weight_lbs: 95
  }),
  ex({
    id: "ex-standing-calf-raise",
    name: "Standing Calf Raise Machine",
    primary_muscle: "calves",
    target_region: "calves",
    movement_pattern: "standing_calf_raise",
    movement_family: "squat",
    required_equipment_ids: ["eq-standing-calf"],
    compatible_equipment_categories: ["Calf Raise"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 180
  }),
  ex({
    id: "ex-seated-calf-raise",
    name: "Seated Calf Raise Machine",
    primary_muscle: "calves",
    target_region: "calves",
    movement_pattern: "seated_calf_raise",
    movement_family: "squat",
    required_equipment_ids: ["eq-seated-calf"],
    compatible_equipment_categories: ["Calf Raise"],
    default_rep_min: 10,
    default_rep_max: 18,
    default_weight_lbs: 90
  }),
  ex({
    id: "ex-glute-drive",
    name: "Glute Drive Machine",
    primary_muscle: "glutes",
    secondary_muscles: ["hamstrings"],
    target_region: "glutes",
    movement_pattern: "glute_drive",
    movement_family: "hinge",
    required_equipment_ids: ["eq-glute-drive"],
    compatible_equipment_categories: ["Glute Drive"],
    default_weight_lbs: 205,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-glute-bias-back-extension",
    name: "Glute Bias Back Extension",
    primary_muscle: "glutes",
    secondary_muscles: ["hamstrings", "lower_back"],
    target_region: "glutes",
    movement_pattern: "glute_bias_back_extension",
    movement_family: "hinge",
    required_equipment_ids: ["eq-back-extension"],
    compatible_equipment_categories: ["Back Extension"],
    equipment_type_preference: ["machine"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 0
  }),
  ex({
    id: "ex-cable-pull-through",
    name: "Cable Pull Through",
    primary_muscle: "glutes",
    secondary_muscles: ["hamstrings", "lower_back"],
    target_region: "glutes",
    movement_pattern: "cable_pull_through",
    movement_family: "hinge",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 70
  }),
  ex({
    id: "ex-cable-glute-kickback",
    name: "Cable Glute Kickback",
    primary_muscle: "glutes",
    secondary_muscles: ["hamstrings"],
    target_region: "glutes",
    movement_pattern: "glute_kickback",
    movement_family: "hinge",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 12,
    default_rep_max: 18,
    default_weight_lbs: 35
  }),
  ex({
    id: "ex-leg-press-calf-raise",
    name: "Leg Press Calf Raise",
    primary_muscle: "calves",
    target_region: "calves",
    movement_pattern: "calf_press",
    movement_family: "squat",
    required_equipment_ids: ["eq-leg-press-45"],
    compatible_equipment_categories: ["Leg Press"],
    default_rep_min: 10,
    default_rep_max: 18,
    default_weight_lbs: 270
  }),
  ex({
    id: "ex-v-squat-calf-raise",
    name: "V Squat Calf Raise",
    primary_muscle: "calves",
    target_region: "calves",
    movement_pattern: "v_squat_calf_raise",
    movement_family: "squat",
    required_equipment_ids: ["eq-v-squat"],
    compatible_equipment_categories: ["Squat Machine"],
    default_rep_min: 10,
    default_rep_max: 18,
    default_weight_lbs: 160
  }),
  ex({
    id: "ex-smith-squat",
    name: "Smith Machine Squat",
    primary_muscle: "quads",
    secondary_muscles: ["glutes", "hamstrings"],
    target_region: "quads",
    movement_pattern: "smith_squat",
    movement_family: "squat",
    required_equipment_ids: ["eq-smith-machine"],
    compatible_equipment_categories: ["Smith Machine"],
    equipment_type_preference: ["smith_machine"],
    default_weight_lbs: 155,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-smith-split-squat",
    name: "Smith Machine Split Squat",
    primary_muscle: "glutes",
    secondary_muscles: ["quads", "hamstrings"],
    target_region: "glutes",
    movement_pattern: "smith_split_squat",
    movement_family: "squat",
    required_equipment_ids: ["eq-smith-machine"],
    compatible_equipment_categories: ["Smith Machine"],
    equipment_type_preference: ["smith_machine"],
    default_weight_lbs: 95,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-preacher-curl-machine",
    name: "Preacher Curl Machine",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "preacher_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-preacher-curl"],
    compatible_equipment_categories: ["Curl Machine"],
    default_rep_min: 8,
    default_rep_max: 12,
    default_weight_lbs: 70
  }),
  ex({
    id: "ex-cable-curl-straight-bar",
    name: "Cable Curl - Straight Bar",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "cable_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 65
  }),
  ex({
    id: "ex-cable-rope-hammer-curl",
    name: "Cable Rope Hammer Curl",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "rope_hammer_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 55
  }),
  ex({
    id: "ex-single-arm-cable-curl",
    name: "Single Arm Cable Curl",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "single_arm_cable_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-cable-crossover"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 25
  }),
  ex({
    id: "ex-cable-bayesian-curl",
    name: "Cable Bayesian Curl",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "bayesian_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 25
  }),
  ex({
    id: "ex-cable-reverse-curl",
    name: "Cable Reverse Curl",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "reverse_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 50
  }),
  ex({
    id: "ex-rope-triceps-pushdown",
    name: "Cable Rope Triceps Pushdown",
    primary_muscle: "triceps",
    target_region: "triceps",
    movement_pattern: "triceps_pushdown",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 70
  }),
  ex({
    id: "ex-straight-bar-triceps-pushdown",
    name: "Straight Bar Triceps Pushdown",
    primary_muscle: "triceps",
    target_region: "triceps",
    movement_pattern: "triceps_pushdown",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_weight_lbs: 80
  }),
  ex({
    id: "ex-cable-overhead-triceps-extension",
    name: "Cable Overhead Triceps Extension",
    primary_muscle: "triceps",
    target_region: "triceps",
    movement_pattern: "overhead_triceps_extension",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 60
  }),
  ex({
    id: "ex-machine-triceps-extension",
    name: "Triceps Extension Machine",
    primary_muscle: "triceps",
    target_region: "triceps",
    movement_pattern: "machine_triceps_extension",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-triceps-extension"],
    compatible_equipment_categories: ["Triceps Extension"],
    default_weight_lbs: 85
  }),
  ex({
    id: "ex-assisted-dip-triceps",
    name: "Assisted Dip - Triceps Bias",
    primary_muscle: "triceps",
    secondary_muscles: ["chest", "front_delt"],
    target_region: "triceps",
    movement_pattern: "assisted_dip",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-assisted-dip"],
    compatible_equipment_categories: ["Assisted Bodyweight"],
    default_weight_lbs: 60,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-dip-machine-triceps",
    name: "Dip Machine - Triceps Bias",
    primary_muscle: "triceps",
    secondary_muscles: ["chest", "front_delt"],
    target_region: "triceps",
    movement_pattern: "machine_dip",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-dip-machine"],
    compatible_equipment_categories: ["Dip Machine"],
    default_weight_lbs: 120,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-crossbody-cable-triceps-extension",
    name: "Crossbody Cable Triceps Extension",
    primary_muscle: "triceps",
    target_region: "triceps",
    movement_pattern: "crossbody_triceps_extension",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-cable-crossover"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 25
  }),
  ex({
    id: "ex-cable-wrist-curl",
    name: "Cable Wrist Curl",
    primary_muscle: "forearms",
    secondary_muscles: ["biceps"],
    target_region: "biceps",
    movement_pattern: "wrist_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_sets: 2,
    default_rep_min: 12,
    default_rep_max: 20,
    default_weight_lbs: 35
  }),
  ex({
    id: "ex-ab-crunch-machine",
    name: "Ab Crunch Machine",
    primary_muscle: "abs",
    secondary_muscles: ["obliques"],
    target_region: "abs",
    movement_pattern: "machine_crunch",
    movement_family: "core",
    required_equipment_ids: ["eq-ab-crunch"],
    compatible_equipment_categories: ["Core Machine"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 85
  }),
  ex({
    id: "ex-cable-crunch",
    name: "Cable Crunch",
    primary_muscle: "abs",
    secondary_muscles: ["obliques"],
    target_region: "abs",
    movement_pattern: "cable_crunch",
    movement_family: "core",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 80
  }),
  ex({
    id: "ex-cable-pallof-press",
    name: "Cable Pallof Press",
    primary_muscle: "abs",
    secondary_muscles: ["obliques"],
    target_region: "obliques",
    movement_pattern: "pallof_press",
    movement_family: "core",
    required_equipment_ids: ["eq-dual-cable-station"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_sets: 2,
    default_rep_min: 10,
    default_rep_max: 12,
    default_weight_lbs: 35,
    fatigue_score: "low"
  }),
  ex({
    id: "ex-cable-wood-chop",
    name: "Cable Wood Chop",
    primary_muscle: "obliques",
    secondary_muscles: ["abs"],
    target_region: "obliques",
    movement_pattern: "wood_chop",
    movement_family: "core",
    required_equipment_ids: ["eq-cable-crossover"],
    compatible_equipment_categories: ["Cable Station"],
    equipment_type_preference: ["cable"],
    default_sets: 2,
    default_rep_min: 10,
    default_rep_max: 12,
    default_weight_lbs: 30
  }),
  ex({
    id: "ex-rotary-torso",
    name: "Rotary Torso Machine",
    primary_muscle: "obliques",
    secondary_muscles: ["abs"],
    target_region: "obliques",
    movement_pattern: "rotary_torso",
    movement_family: "core",
    required_equipment_ids: ["eq-rotary-torso"],
    compatible_equipment_categories: ["Core Machine"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 70
  }),
  ex({
    id: "ex-back-extension",
    name: "Back Extension",
    primary_muscle: "lower_back",
    secondary_muscles: ["glutes", "hamstrings"],
    target_region: "lower_back",
    movement_pattern: "back_extension",
    movement_family: "hinge",
    required_equipment_ids: ["eq-back-extension"],
    compatible_equipment_categories: ["Back Extension"],
    equipment_type_preference: ["machine"],
    default_rep_min: 10,
    default_rep_max: 15,
    default_weight_lbs: 0
  }),
  ex({
    id: "ex-treadmill-incline-walk",
    name: "Treadmill Incline Walk",
    primary_muscle: "cardio",
    secondary_muscles: ["calves", "glutes", "quads"],
    target_region: "cardio",
    movement_pattern: "incline_walk",
    movement_family: "cardio",
    required_equipment_ids: ["eq-treadmill"],
    compatible_equipment_categories: ["Cardio"],
    equipment_type_preference: ["cardio"],
    default_sets: 1,
    default_rep_min: 10,
    default_rep_max: 20,
    default_rest_seconds: 0,
    fatigue_score: "medium",
    progression_type: "duration"
  }),
  ex({
    id: "ex-stair-climber-intervals",
    name: "Stair Climber Intervals",
    primary_muscle: "cardio",
    secondary_muscles: ["glutes", "quads", "calves"],
    target_region: "cardio",
    movement_pattern: "stair_climb",
    movement_family: "cardio",
    required_equipment_ids: ["eq-stair-climber"],
    compatible_equipment_categories: ["Cardio"],
    equipment_type_preference: ["cardio"],
    default_sets: 1,
    default_rep_min: 8,
    default_rep_max: 15,
    default_rest_seconds: 0,
    fatigue_score: "medium_high",
    progression_type: "duration"
  }),
  ex({
    id: "ex-bike-zone-2",
    name: "Stationary Bike Zone 2",
    primary_muscle: "cardio",
    secondary_muscles: ["quads", "hamstrings"],
    target_region: "cardio",
    movement_pattern: "bike_zone_2",
    movement_family: "cardio",
    required_equipment_ids: ["eq-stationary-bike"],
    compatible_equipment_categories: ["Cardio"],
    equipment_type_preference: ["cardio"],
    default_sets: 1,
    default_rep_min: 15,
    default_rep_max: 30,
    default_rest_seconds: 0,
    fatigue_score: "low",
    progression_type: "duration"
  }),
  ex({
    id: "ex-bike-intervals",
    name: "Stationary Bike Intervals",
    primary_muscle: "cardio",
    secondary_muscles: ["quads", "glutes", "calves"],
    target_region: "cardio",
    movement_pattern: "bike_intervals",
    movement_family: "cardio",
    required_equipment_ids: ["eq-stationary-bike"],
    compatible_equipment_categories: ["Cardio"],
    equipment_type_preference: ["cardio"],
    default_sets: 1,
    default_rep_min: 8,
    default_rep_max: 12,
    default_rest_seconds: 0,
    fatigue_score: "medium",
    progression_type: "duration"
  }),
  ex({
    id: "ex-barbell-bench-press",
    name: "Barbell Bench Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt"],
    target_region: "mid_chest",
    movement_pattern: "barbell_bench_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-olympic-barbell", "eq-flat-bench", "eq-bench-press-rack"],
    equipment_requirement: {
      allOf: ["eq-olympic-barbell"],
      oneOfGroups: [["eq-flat-bench", "eq-adjustable-bench"], ["eq-bench-press-rack", "eq-power-rack"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench", "Rack"],
    equipment_type_preference: ["barbell"],
    exercise_role: "primary_compound",
    default_sets: 4,
    default_rep_min: 6,
    default_rep_max: 10,
    default_warmup_sets: 3,
    default_rest_seconds: 150,
    default_weight_lbs: 135,
    fatigue_score: "high",
    technical_difficulty: "medium"
  }),
  ex({
    id: "ex-incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    primary_muscle: "chest",
    secondary_muscles: ["front_delt", "triceps"],
    target_region: "upper_chest",
    movement_pattern: "incline_dumbbell_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-dumbbell-set", "eq-adjustable-bench"],
    equipment_requirement: {
      allOf: ["eq-dumbbell-set"],
      oneOfGroups: [["eq-adjustable-bench"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "secondary_compound",
    default_sets: 3,
    default_rep_min: 8,
    default_rep_max: 12,
    default_warmup_sets: 1,
    default_rest_seconds: 120,
    default_weight_lbs: 60,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    primary_muscle: "chest",
    secondary_muscles: ["triceps", "front_delt"],
    target_region: "mid_chest",
    movement_pattern: "dumbbell_bench_press",
    movement_family: "horizontal_push",
    required_equipment_ids: ["eq-dumbbell-set", "eq-flat-bench"],
    equipment_requirement: {
      allOf: ["eq-dumbbell-set"],
      oneOfGroups: [["eq-flat-bench", "eq-adjustable-bench"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "secondary_compound",
    default_sets: 3,
    default_rep_min: 8,
    default_rep_max: 12,
    default_warmup_sets: 1,
    default_rest_seconds: 120,
    default_weight_lbs: 65,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-dumbbell-fly",
    name: "Dumbbell Fly",
    primary_muscle: "chest",
    secondary_muscles: ["front_delt"],
    target_region: "mid_chest",
    movement_pattern: "dumbbell_fly",
    movement_family: "fly",
    required_equipment_ids: ["eq-dumbbell-set", "eq-flat-bench"],
    equipment_requirement: {
      allOf: ["eq-dumbbell-set"],
      oneOfGroups: [["eq-flat-bench", "eq-adjustable-bench"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "primary_isolation",
    default_sets: 3,
    default_rep_min: 10,
    default_rep_max: 15,
    default_rest_seconds: 75,
    default_weight_lbs: 30,
    fatigue_score: "medium"
  }),
  ex({
    id: "ex-barbell-bent-over-row",
    name: "Barbell Bent-Over Row",
    primary_muscle: "mid_back",
    secondary_muscles: ["lats", "biceps", "rear_delt", "lower_back"],
    target_region: "mid_back",
    movement_pattern: "barbell_bent_over_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-olympic-barbell"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["barbell"],
    exercise_role: "primary_compound",
    default_sets: 4,
    default_rep_min: 6,
    default_rep_max: 10,
    default_warmup_sets: 2,
    default_rest_seconds: 150,
    default_weight_lbs: 135,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-one-arm-dumbbell-row",
    name: "One-Arm Dumbbell Row",
    primary_muscle: "lats",
    secondary_muscles: ["mid_back", "biceps", "rear_delt"],
    target_region: "lats",
    movement_pattern: "one_arm_dumbbell_row",
    movement_family: "horizontal_pull",
    required_equipment_ids: ["eq-dumbbell-set", "eq-flat-bench"],
    equipment_requirement: {
      allOf: ["eq-dumbbell-set"],
      oneOfGroups: [["eq-flat-bench", "eq-adjustable-bench"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "secondary_compound",
    default_sets: 3,
    default_rep_min: 8,
    default_rep_max: 12,
    default_rest_seconds: 105,
    default_weight_lbs: 70,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-dumbbell-pullover",
    name: "Dumbbell Pullover",
    primary_muscle: "lats",
    secondary_muscles: ["chest", "triceps"],
    target_region: "lats",
    movement_pattern: "dumbbell_pullover",
    movement_family: "shoulder_extension",
    required_equipment_ids: ["eq-dumbbell-set", "eq-flat-bench"],
    equipment_requirement: {
      allOf: ["eq-dumbbell-set"],
      oneOfGroups: [["eq-flat-bench", "eq-adjustable-bench"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "primary_isolation",
    default_sets: 3,
    default_rep_min: 10,
    default_rep_max: 15,
    default_rest_seconds: 90,
    default_weight_lbs: 55
  }),
  ex({
    id: "ex-barbell-overhead-press",
    name: "Barbell Overhead Press",
    primary_muscle: "front_delt",
    secondary_muscles: ["triceps", "side_delt", "traps", "abs"],
    target_region: "front_delt",
    movement_pattern: "barbell_overhead_press",
    movement_family: "vertical_push",
    required_equipment_ids: ["eq-olympic-barbell"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["barbell"],
    exercise_role: "primary_compound",
    default_sets: 4,
    default_rep_min: 6,
    default_rep_max: 10,
    default_warmup_sets: 2,
    default_rest_seconds: 150,
    default_weight_lbs: 95,
    fatigue_score: "high",
    technical_difficulty: "high"
  }),
  ex({
    id: "ex-dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    primary_muscle: "front_delt",
    secondary_muscles: ["triceps", "side_delt"],
    target_region: "front_delt",
    movement_pattern: "dumbbell_shoulder_press",
    movement_family: "vertical_push",
    required_equipment_ids: ["eq-dumbbell-set", "eq-adjustable-bench"],
    equipment_requirement: {
      allOf: ["eq-dumbbell-set"],
      oneOfGroups: [["eq-adjustable-bench"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "secondary_compound",
    default_sets: 3,
    default_rep_min: 8,
    default_rep_max: 12,
    default_warmup_sets: 1,
    default_rest_seconds: 120,
    default_weight_lbs: 50,
    fatigue_score: "medium_high"
  }),
  ex({
    id: "ex-dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    primary_muscle: "side_delt",
    secondary_muscles: ["traps"],
    target_region: "side_delt",
    movement_pattern: "dumbbell_lateral_raise",
    movement_family: "shoulder_abduction",
    required_equipment_ids: ["eq-dumbbell-set"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "primary_isolation",
    default_sets: 4,
    default_rep_min: 12,
    default_rep_max: 20,
    default_rest_seconds: 60,
    default_weight_lbs: 20,
    fatigue_score: "low",
    technical_difficulty: "low"
  }),
  ex({
    id: "ex-bent-over-dumbbell-rear-delt-raise",
    name: "Bent-Over Dumbbell Rear Delt Raise",
    primary_muscle: "rear_delt",
    secondary_muscles: ["upper_back", "traps"],
    target_region: "rear_delt",
    movement_pattern: "bent_over_dumbbell_rear_delt_raise",
    movement_family: "fly",
    required_equipment_ids: ["eq-dumbbell-set"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "primary_isolation",
    default_sets: 4,
    default_rep_min: 12,
    default_rep_max: 20,
    default_rest_seconds: 60,
    default_weight_lbs: 20,
    fatigue_score: "low",
    technical_difficulty: "low"
  }),
  ex({
    id: "ex-ez-bar-upright-row",
    name: "EZ-Bar Upright Row",
    primary_muscle: "side_delt",
    secondary_muscles: ["traps", "biceps"],
    target_region: "side_delt",
    movement_pattern: "ez_bar_upright_row",
    movement_family: "shoulder_abduction",
    required_equipment_ids: ["eq-ez-curl-bar"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["barbell"],
    exercise_role: "accessory",
    default_sets: 3,
    default_rep_min: 10,
    default_rep_max: 15,
    default_rest_seconds: 75,
    default_weight_lbs: 50
  }),
  ex({
    id: "ex-barbell-back-squat",
    name: "Barbell Back Squat",
    primary_muscle: "quads",
    secondary_muscles: ["glutes", "hamstrings", "abs", "lower_back"],
    target_region: "quads",
    movement_pattern: "barbell_back_squat",
    movement_family: "squat",
    required_equipment_ids: ["eq-olympic-barbell", "eq-squat-rack"],
    equipment_requirement: {
      allOf: ["eq-olympic-barbell"],
      oneOfGroups: [["eq-squat-rack", "eq-power-rack"]]
    },
    compatible_equipment_categories: ["Free Weight", "Rack"],
    equipment_type_preference: ["barbell"],
    exercise_role: "primary_compound",
    default_sets: 4,
    default_rep_min: 5,
    default_rep_max: 8,
    default_warmup_sets: 3,
    default_rest_seconds: 180,
    default_weight_lbs: 185,
    fatigue_score: "high",
    technical_difficulty: "high"
  }),
  ex({
    id: "ex-romanian-deadlift",
    name: "Romanian Deadlift",
    primary_muscle: "hamstrings",
    secondary_muscles: ["glutes", "lower_back"],
    target_region: "hamstrings",
    movement_pattern: "romanian_deadlift",
    movement_family: "hinge",
    required_equipment_ids: ["eq-olympic-barbell"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["barbell"],
    exercise_role: "primary_compound",
    default_sets: 4,
    default_rep_min: 6,
    default_rep_max: 10,
    default_warmup_sets: 2,
    default_rest_seconds: 150,
    default_weight_lbs: 185,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-dumbbell-bulgarian-split-squat",
    name: "Dumbbell Bulgarian Split Squat",
    primary_muscle: "quads",
    secondary_muscles: ["glutes", "hamstrings"],
    target_region: "quads",
    movement_pattern: "dumbbell_bulgarian_split_squat",
    movement_family: "squat",
    required_equipment_ids: ["eq-dumbbell-set", "eq-flat-bench"],
    equipment_requirement: {
      allOf: ["eq-dumbbell-set"],
      oneOfGroups: [["eq-flat-bench", "eq-adjustable-bench"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "unilateral_compound",
    default_sets: 3,
    default_rep_min: 8,
    default_rep_max: 12,
    default_rest_seconds: 120,
    default_weight_lbs: 50,
    fatigue_score: "high"
  }),
  ex({
    id: "ex-dumbbell-curl",
    name: "Dumbbell Curl",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "dumbbell_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-dumbbell-set"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "primary_isolation",
    default_sets: 3,
    default_rep_min: 10,
    default_rep_max: 15,
    default_rest_seconds: 75,
    default_weight_lbs: 30
  }),
  ex({
    id: "ex-hammer-curl",
    name: "Hammer Curl",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "hammer_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-dumbbell-set"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "secondary_isolation",
    default_sets: 3,
    default_rep_min: 10,
    default_rep_max: 15,
    default_rest_seconds: 75,
    default_weight_lbs: 30
  }),
  ex({
    id: "ex-ez-bar-curl",
    name: "EZ-Bar Curl",
    primary_muscle: "biceps",
    secondary_muscles: ["forearms"],
    target_region: "biceps",
    movement_pattern: "ez_bar_curl",
    movement_family: "elbow_flexion",
    required_equipment_ids: ["eq-ez-curl-bar"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["barbell"],
    exercise_role: "primary_isolation",
    default_sets: 3,
    default_rep_min: 8,
    default_rep_max: 12,
    default_rest_seconds: 75,
    default_weight_lbs: 60
  }),
  ex({
    id: "ex-dumbbell-overhead-triceps-extension",
    name: "Dumbbell Overhead Triceps Extension",
    primary_muscle: "triceps",
    secondary_muscles: [],
    target_region: "triceps",
    movement_pattern: "dumbbell_overhead_triceps_extension",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-dumbbell-set"],
    compatible_equipment_categories: ["Free Weight"],
    equipment_type_preference: ["dumbbell"],
    exercise_role: "primary_isolation",
    default_sets: 3,
    default_rep_min: 10,
    default_rep_max: 15,
    default_rest_seconds: 75,
    default_weight_lbs: 55
  }),
  ex({
    id: "ex-ez-bar-skull-crusher",
    name: "EZ-Bar Skull Crusher",
    primary_muscle: "triceps",
    secondary_muscles: ["chest"],
    target_region: "triceps",
    movement_pattern: "ez_bar_skull_crusher",
    movement_family: "elbow_extension",
    required_equipment_ids: ["eq-ez-curl-bar", "eq-flat-bench"],
    equipment_requirement: {
      allOf: ["eq-ez-curl-bar"],
      oneOfGroups: [["eq-flat-bench", "eq-adjustable-bench"]]
    },
    compatible_equipment_categories: ["Free Weight", "Bench"],
    equipment_type_preference: ["barbell"],
    exercise_role: "primary_isolation",
    default_sets: 3,
    default_rep_min: 8,
    default_rep_max: 12,
    default_rest_seconds: 90,
    default_weight_lbs: 60
  })
];

export function getExerciseById(id: string, exercises = exerciseCatalog) {
  return exercises.find((exercise) => exercise.id === id);
}
