const koreanLabels: Record<string, string> = {
  machine: "머신",
  cable: "케이블",
  barbell: "바벨",
  dumbbell: "덤벨",
  bodyweight: "맨몸",
  smith_machine: "스미스 머신",
  cardio: "유산소",
  accessory: "액세서리",
  plate_loaded: "원판 로딩",
  selectorized: "핀 로딩",
  cable_stack: "케이블 스택",
  free_weight: "프리웨이트",
  assisted: "보조",
  unknown: "알 수 없음",
  horizontal_push: "수평 밀기",
  vertical_push: "수직 밀기",
  horizontal_pull: "수평 당기기",
  vertical_pull: "수직 당기기",
  squat: "스쿼트/프레스",
  hinge: "힌지",
  knee_extension: "무릎 신전",
  knee_flexion: "무릎 굴곡",
  hip_abduction: "고관절 외전",
  hip_adduction: "고관절 내전",
  elbow_flexion: "팔꿈치 굴곡",
  elbow_extension: "팔꿈치 신전",
  shoulder_abduction: "어깨 외전",
  shoulder_extension: "어깨 신전",
  fly: "플라이",
  core: "코어",
  chest: "가슴",
  triceps: "삼두",
  front_delt: "전면 어깨",
  side_delt: "측면 어깨",
  rear_delt: "후면 어깨",
  lats: "광배",
  upper_back: "상부 등",
  mid_back: "중부 등",
  lower_back: "하부 등",
  traps: "승모",
  biceps: "이두",
  forearms: "전완",
  quads: "대퇴사두",
  hamstrings: "햄스트링",
  glutes: "둔근",
  calves: "종아리",
  abs: "복근",
  obliques: "복사근",
  adductors: "내전근",
  abductors: "외전근",
  upper_chest: "상부 가슴",
  mid_chest: "중부 가슴",
  lower_chest: "하부 가슴",
  flat: "플랫",
  incline: "인클라인",
  decline: "디클라인",
  vertical: "수직",
  horizontal: "수평",
  high_to_low: "하이 투 로우",
  low_to_high: "로우 투 하이",
  neutral: "중립",
  rotational: "회전",
  mixed: "혼합",
  low: "낮음",
  medium: "보통",
  medium_high: "약간 높음",
  high: "높음",
  preferred: "선호",
  avoid: "피하기",
  disabled: "비활성",
  load: "중량",
  reps: "반복수",
  tempo: "템포",
  range_of_motion: "가동 범위",
  duration: "시간",
  normal: "보통",
  push: "푸시",
  pull: "풀",
  legs: "하체",
  upper: "상체",
  lower: "하체 집중",
  full_body: "전신",
  rest: "휴식",
  machine_only: "머신만",
  machine_cable_priority: "머신/케이블 우선",
  free_weight_allowed: "프리웨이트 허용",
  decline_press: "디클라인 프레스",
  incline_press: "인클라인 프레스",
  flat_press: "플랫 프레스",
  close_grip_press: "클로즈 그립 프레스",
  pec_deck_fly: "펙덱 플라이",
  high_to_low_cable_fly: "하이 투 로우 케이블 플라이",
  low_to_high_cable_fly: "로우 투 하이 케이블 플라이",
  cable_press: "케이블 프레스",
  assisted_dip: "어시스트 딥",
  smith_incline_press: "스미스 인클라인 프레스",
  smith_decline_press: "스미스 디클라인 프레스",
  single_arm_cable_press: "싱글암 케이블 프레스",
  cross_body_fly: "크로스 바디 플라이",
  wide_pulldown: "와이드 풀다운",
  neutral_pulldown: "뉴트럴 풀다운",
  reverse_grip_pulldown: "리버스 그립 풀다운",
  neutral_cable_row: "뉴트럴 케이블 로우",
  wide_cable_row: "와이드 케이블 로우",
  chest_supported_row: "체스트 서포티드 로우",
  prime_row: "프라임 로우",
  high_row: "하이 로우",
  diagonal_row: "대각선 로우",
  low_row: "로우 로우",
  tbar_row: "티바 로우",
  machine_pullover: "머신 풀오버",
  straight_arm_pulldown: "스트레이트암 풀다운",
  cable_pullover: "케이블 풀오버",
  rear_delt_fly: "리어델트 플라이",
  face_pull: "페이스 풀",
  single_arm_cable_row: "싱글암 케이블 로우",
  machine_shoulder_press: "머신 숄더 프레스",
  neutral_shoulder_press: "뉴트럴 숄더 프레스",
  machine_lateral_raise: "머신 레터럴 레이즈",
  cable_lateral_raise: "케이블 레터럴 레이즈",
  lean_away_cable_lateral_raise: "린어웨이 케이블 레터럴 레이즈",
  rear_delt_cable_fly: "리어델트 케이블 플라이",
  cable_front_raise: "케이블 프론트 레이즈",
  cable_y_raise: "케이블 Y 레이즈",
  smith_upright_row: "스미스 업라이트 로우",
  external_rotation: "외회전",
  hack_squat: "핵 스쿼트",
  v_squat: "브이 스쿼트",
  leg_press_45: "45도 레그 프레스",
  horizontal_leg_press: "수평 레그 프레스",
  leg_extension: "레그 익스텐션",
  single_leg_extension: "싱글 레그 익스텐션",
  seated_leg_curl: "시티드 레그 컬",
  lying_leg_curl: "라잉 레그 컬",
  single_leg_curl: "싱글 레그 컬",
  standing_calf_raise: "스탠딩 카프 레이즈",
  seated_calf_raise: "시티드 카프 레이즈",
  glute_drive: "글루트 드라이브",
  glute_bias_back_extension: "둔근 중심 백 익스텐션",
  cable_pull_through: "케이블 풀스루",
  glute_kickback: "글루트 킥백",
  calf_press: "카프 프레스",
  v_squat_calf_raise: "브이 스쿼트 카프 레이즈",
  smith_squat: "스미스 스쿼트",
  smith_split_squat: "스미스 스플릿 스쿼트",
  preacher_curl: "프리처 컬",
  cable_curl: "케이블 컬",
  rope_hammer_curl: "로프 해머 컬",
  single_arm_cable_curl: "싱글암 케이블 컬",
  bayesian_curl: "베이지안 컬",
  reverse_curl: "리버스 컬",
  triceps_pushdown: "트라이셉스 푸시다운",
  overhead_triceps_extension: "오버헤드 트라이셉스 익스텐션",
  machine_triceps_extension: "머신 트라이셉스 익스텐션",
  machine_dip: "머신 딥",
  crossbody_triceps_extension: "크로스바디 트라이셉스 익스텐션",
  wrist_curl: "손목 컬",
  machine_crunch: "머신 크런치",
  cable_crunch: "케이블 크런치",
  pallof_press: "팔로프 프레스",
  wood_chop: "우드 촙",
  rotary_torso: "로터리 토르소",
  back_extension: "백 익스텐션",
  incline_walk: "인클라인 걷기",
  stair_climb: "스텝 클라이머",
  bike_zone_2: "실내 자전거 존2",
  bike_intervals: "실내 자전거 인터벌"
};

export function titleCase(value: string) {
  return koreanLabels[value] ?? value.replaceAll("_", " ");
}

export function compactList(values: string[], max = 3) {
  if (values.length <= max) return values.map(titleCase).join(", ");
  return `${values.slice(0, max).map(titleCase).join(", ")} +${values.length - max}`;
}
